#!/bin/bash
#script that generates all the needed .html files from a template. 
#The only difference between the different pages is one "include" of 
#the content file, so we use sed to replace "CONTENT" in the template with 
#the actual subpage name

cd content

for SUBPAGE in *.html
do
	echo $SUBPAGE
	sed "s/CONTENT/$SUBPAGE/" ../page_template > ../$SUBPAGE
done

cd ..


#also generate publications and talks content...

bibtex2html -nokeys -nodoc -dl -d -r -o generated_publications papers/publications.bib
bibtex2html -nokeys -nodoc -nf ppt ".ppt" -dl -d -r -o generated_talks talks/talks.bib

