#!/bin/bash
#script that generates all the needed .html files from a template. 
#The only difference between the different pages is one "include" of 
#the content file, so we use sed to replace "CONTENT" in the template with 
#the actual subpage name

# generate publications and talks content...

echo Creating publications and talks...
for CATEGORY in javagat satin mpj gmi zorilla ibis smartsockets other
do
    echo $CATEGORY
    if [ -f publications/$CATEGORY.bib ]
    then
	bibtex2html -nokeys -nofooter -nodoc -dl -d -r -q -o generated/publications_$CATEGORY publications/$CATEGORY.bib
    else
	echo "Warning: publications/$CATEGORY.bib is missing" 1>&2
    fi

    if [ -f talks/$CATEGORY.bib ]
    then
	bibtex2html -nokeys -nofooter -nodoc -nf ppt ".ppt" -dl -d -r -q -o generated/talks_$CATEGORY talks/$CATEGORY.bib
    else
	echo "Warning: talks/$CATEGORY.bib is missing" 1>&2
    fi
done
